export const CONFIG_TABLE_COLUMN = [
  {
    title: 'STT',
    priority: 0,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'Name',
    priority: 1,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'Location',
    priority: 2,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'Status',
    priority: 3,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'Available',
    priority: 4,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'Description',
    priority: 5,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'IdentityDevice',
    priority: 6,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'TimeOffAgo',
    priority: 7,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'UpDatetime',
    priority: 8,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'InsDatetime',
    priority: 9,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
];
