export const CONFIG_TABLE_COLUMN = [
  {
    title: 'STT',
    priority: 0,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'Tên thiết bị',
    priority: 1,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'Trạng thái',
    priority: 2,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'Trình chiếu',
    priority: 3,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'Đang chạy',
    priority: 4,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'Mất kết nối',
    priority: 5,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'Hoạt động gần nhất',
    priority: 6,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'Vị trí',
    priority: 7,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'Model máy',
    priority: 8,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'Số series',
    priority: 9,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'Hãng sản xuất',
    priority: 10,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'Phiên bản app đang cài đặt',
    priority: 11,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'Phiên bản hệ điều hành',
    priority: 10,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: '',
    priority: 11,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
];
