pipeline {
    agent any

    tools {
        nodejs "NodeJS 16.18.0"
    }

    environment {
        GITHUB_CREDENTIALS_ID = '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'  // ID của thông tin xác thực bạn đã tạo
    }

    stages {
        stage('Checkout') {
            steps {
                // Clone the repository
                git branch: 'dev/adv', url: 'https://github.com/DungLV1520/FE-Center.git', credentialsId: env.GITHUB_CREDENTIALS_ID
            }
        }

        stage('Copy to /var/www/html') {
            steps {
                // Remove old files and copy new build artifacts
                sh '''
                    sudo cp -rf /var/lib/jenkins/workspace/ADV/dist/** /var/www/html/hub
                '''
            }
        }
    }

    post {
        success {
            echo 'Build and deployment succeeded!'
        }
        failure {
            echo 'Build or deployment failed!'
        }
    }
}
