pipeline {
    agent any

    tools {
        nodejs "NodeJS 16.18.0"
    }

    environment {
        GITHUB_CREDENTIALS_ID = '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'  // ID của thông tin xác thực bạn đã tạo
    }

    stages {
        stage('Checkout') {
            steps {
                // Clone the repository
                git branch: 'dev/adv', url: 'https://github.com/DungLV1520/FE-Center.git'
            }
        }

        stage('Install dependencies') {
            steps {
                // Install npm dependencies
                sh 'npm install --force'
            }
        }

        stage('Build') {
            steps {
                // Build the Angular project
                sh 'npx nx run hub-center:build'
            }
        }

        stage('Archive') {
            steps {
                // Archive the build artifacts
                archiveArtifacts artifacts: 'dist/**', allowEmptyArchive: true
            }
        }

        stage('Deploy') {
            steps {
                // Example deploy step, customize it based on your deployment strategy
                sh 'echo "Deploy step"'
            }
        }
    }

    post {
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
