export const CONFIG_TABLE_COLUMN = [
  {
    title: 'STT',
    priority: 0,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'Tên',
    priority: 1,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'Email',
    priority: 2,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'SĐT',
    priority: 3,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'Username',
    priority: 4,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: 'Vai trò',
    priority: 6,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: "Trạng thái",
    priority: 7,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: "Ngày hết hạn",
    priority: 7,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: "Ngày tạo",
    priority: 7,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
  {
    title: "",
    priority: 7,
    listOfFilter: [],
    filterFn: null,
    filterMultiple: true,
  },
];
